bookMeni/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

source/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from calender import views as calendar_views
from user import views as user_views
from articles import views as articles_views
from rest_framework.authtoken.views import obtain_auth_token

from rest_framework.routers import DefaultRouter
router = DefaultRouter()
from user.authentication import CustomAuthToken

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('articles/', include('articles.urls.articles_urls')),
    path('account/', include('allauth.urls')),
    path('calendar/', include('calender.urls')),
    path('user/', include('user.urls')),
    path('gettoken/', CustomAuthToken.as_view())

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from .views import UserRegisterView, ChangePasswordView, profile, register, UpdateProfileView
from django.contrib.auth.views import LogoutView

# app_name = 'account'

urlpatterns = [

    path('register/', register, name='register'),
    # path('login/', UserLoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('profile/<str:username>/', profile, name='profile'),
    path('<int:pk>/update', UpdateProfileView.as_view(),name='update_profile')
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model

class Author(models.Model):
    first_name = models.CharField(max_length=50, null=False, blank=False)
    last_name = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Article(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    author = models.ForeignKey(
        get_user_model(),
        on_delete = models.SET_DEFAULT,
        default = 1,
        related_name = 'article'
    )
    body = models.TextField(max_length=3000, null=False, blank=False)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(
        'articles.Tag',
        related_name = 'articles',
        blank = True
    )

    def __str__(self):
        return f'{self.pk}.{self.title}'

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
        permissions = [
            ('can_read_article', '有权限读文章')
        ]

    @classmethod
    def create_permissions(cls):
        content_type = ContentType.objects.get_for_model(cls)
        Permission.objects.get_or_create(
            codename='view_article',
            name='Can view article',
            content_type=content_type,
        )

class Comment(models.Model):
    article = models.ForeignKey('articles.Article', on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(max_length=500)
    author = models.ForeignKey(
        get_user_model(),
        on_delete = models.SET_DEFAULT,
        default = 1,
        related_name = 'comment'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text[:20]

class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='Tag')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

articles/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Comment, Author, Article

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('text',)

class ArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=200, required=True, label='Article name')

    class Meta:
        model = Article
        fields = ('title', 'author', 'body')

class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Search')

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

articles/helpers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView


class ParamMixin:
    form_class = None
    template_name = None
    redirect_url = ''
    model = None
    context_object_key = 'object'
    key_kwargs = 'pk'
    kwargs = None
    _object = None

    def get_object(self):
        pk = self.kwargs.get(self.key_kwargs)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url

class CustomFormView(View, ParamMixin):

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_context_data(self, **kwargs):
        return kwargs

class CustomListView(TemplateView, ParamMixin):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_object_key] = self.get_object()
        return context

    def get_objects(self):
        return self.model.objects.filter(is_deleted=False)

class CustomDetailView(TemplateView, ParamMixin):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_object_key] = self.get_object()
        return context

class CustomCreateView(View, ParamMixin):

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request=request, template_name=self.template_name, context=context)

    def get_context_data(self, **kwargs):
        return kwargs

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(request=self.request, template_name=self.template_name, context=context)

class CustomUpdateView(View, ParamMixin):

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object)
        context = self.get_context_data(form=form)
        return render(request, template_name=self.template_name, context=context)

    def get_context_data(self, **kwargs):
        context = self.kwargs.copy()
        context[self.context_object_name] = self.object
        context.update(kwargs)
        return context

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self,form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class CustomDeleteView(View, ParamMixin):
    confirm_deletion = True

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect('home')

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_object_name: self.object}

articles/views/articles_view.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import urlencode
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from ..forms import ArticleForm, SearchForm
from ..helpers.views import CustomCreateView, CustomUpdateView, CustomDeleteView
from ..models import Article, Author, Tag

class ArticleCreateView(CustomCreateView, CreateView):
    template_name = 'articles/create.html'
    form_class = ArticleForm
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = get_user_model().objects.all()
        context['tags'] = Tag.objects.all()
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_redirect_url(self):
        return reverse('article_detail', kwargs={'pk': self.object.pk})


class ArticleListView(ListView):
    model = Article
    context_object_name = 'articles'
    template_name = 'articles/list.html'
    ordering = ['-created_at']
    paginate_by = 5
    paginate_orphans = 1
    form = SearchForm

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return self.form(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(title__icontains=self.search_value) | Q(author__first_name__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

def article_detail_view(request, *args, **kwargs):
    article = get_object_or_404(Article, pk=kwargs.get('pk'))
    return render(request, 'articles/detail.html', context={'article': article})

class ArticleDetailView( DetailView):
    template_name = 'articles/detail.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.object
        comments = article.comments.order_by('-created_at')
        context['comments'] = comments
        return context


class ArticleUpdateView(PermissionRequiredMixin, CustomUpdateView):
    template_name = 'articles/update.html'
    form_class = ArticleForm
    model = Article
    context_object_name = 'article'
    permission_required = ['articles.change_article']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = get_user_model().objects.all()
        return context

    def get_redirect_url(self):
        return reverse('article_detail', kwargs={'pk': self.object.pk})


class ArticleDeleteView(CustomDeleteView):
    template_name = 'articles/delete.html'
    model = Article
    context_object_name = 'article'
    success_url = reverse_lazy('profile')

    def perform_delete(self):
        self.object.is_deleted = True
        self.object.save()

articles/views/author_views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.model import get_user_model
from ..models import Author
from ..forms import AuthorForm

class AuthorCreateView(CreateView):
    model = Author
    template_name = 'authors/create.html'
    form_class = AuthorForm
    success_url = reverse_lazy('author_list')
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['link'] = reverse('author_create')
        return context


class AuthorListView(ListView):
    template_name = 'author/list.html'
    model = get_user_model()
    context_object_key = 'users'
    paginate_by = 5
    paginate_orphans = 1


class AuthorUpdateView(UpdateView):
    model = Author
    template_name = 'authors/update.html'
    form_class = AuthorForm
    success_url = reverse_lazy('author_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['link'] = reverse('author_update', kwargs={'pk': self.kwargs.get('pk')})
        return context
    
class AuthorDeleteView(DeleteView):
    model = Author
    success_url = reverse_lazy('author_list')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

articles/views/comment_views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin
from ..forms import CommentForm
from ..helpers.views import CustomCreateView, CustomUpdateView, CustomDeleteView
from ..models import Article, Comment

class CommentCreateView(CustomCreateView):
    model = Comment
    template_name = 'comments/create.html'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article'] = self.get_article()
        return context

    def form_valid(self, form):
        form.instance.article = self.get_article()
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_article(self):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        return article

    def get_redirect_url(self):
        return reverse('article_detail', kwargs={'pk': self.object.article.pk})

class CommentUpdateView(UserPassesTestMixin, CustomUpdateView):
    model = Comment
    template_name = 'comments/update.html'
    form_class = CommentForm
    context_object_name = 'comment'
    
    def test_func(self):
        comment = self.get_object()
        return comment.author == self.request.user

    def get_redirect_url(self):
        return reverse('article_detail', kwargs={'pk': self.object.article.pk})

class CommentDeleteView(UserPassesTestMixin, CustomDeleteView):
    model = Comment
    confirm_deletion = False
    context_object_name = 'comment'
    success_url = reverse_lazy('article_list')

    def test_func(self):
        comment = self.get_object()
        return comment.author == self.request.user

    def get_redirect_url(self):
        return reverse_lazy('article_detail', kwargs={'pk': self.object.article.pk})

templates/articles/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Create Position</h1>

<form action="{% url 'article_create' %}" method="POST">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}

    <!-- <div class="mb-3">
        {{ form.title|as_crispy_field }}
        {% for error in form.title.errors %}
            <div style="color:red; font-size: 10px;">{{ error }}</div>
        {% endfor %}
    </div> -->

    <div class="mb-3">
        <!-- {{ form.body|as_crispy_field }} -->
        {{ form|crispy }}
    </div>

    <div class="mb-3">
        <select class="form-select" multiple aria-label="multiple select example" name="tags">
            {% for tag in tags %}
                <option value="{{ tag.id }}">{{ tag }}</option>
            {% endfor %}
        </select>
    </div>

    {% for error in form.tag.errors %}
        <div style="color:red; font-size: 10px;">{{ error }}</div>
    {% endfor %}


    <button type="submit" class="btn btn-success">Create</button>
</form>
{% endblock%}

templates/articles/delete.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h3> Delete Positions {{ article }}</h3>
        <form action="{% url 'article_delete' article.pk %}" method="POST">
            {% csrf_token %}
            <div class="card-body">
                <p class="card-text">Are you sure on deleting this Position {{ article.pk }}?</p>
                <div>
                  <button type="submit" class="btn btn-danger">Delete this article</button>
                  <a class="btn btn-light" href="{% url 'article_detail' article.pk %}" role="button">Cancel</a>
                </div>
            </div>
        </form>
    </div>
 {% endblock %}

templates/articles/detail.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ article.title }}</h2>
            <h5 class="card-title">{{ article.author }}</h5>
            <p class="card-text">{{ article.body }}</p>
            <div>
                  {% if perms.articles.change_article %}
                      <a class="btn btn-primary" href="{% url 'article_update' article.pk %}" role="button">Edit this Position</a>
                  {% endif %}
                  {% if perms.articles.delete_article %}
                      <a class="btn btn-danger" href="{% url 'article_delete' article.pk %}" role="button">Delete this Position</a>
                  {% endif %}
            </div>

            <div calss="mt-5">
              Tags: {% for tag in article.tags.all %}
                {{ tag.name }}{% if not forloop.last %}, {% endif %}
              {% endfor %} 
            </div>
        </div>
      </div>

      <div class="mt-5">
        <ul class="list-group">
          {% for comment in comments %}
            <li class="list-group-item mb-3">
              <div> @{{comment.author }}</div> 
              <div>{{ comment.text }} </div>
              <div style="font-size: 10px; color: grey;"> {{comment.created_at}} </div>
              <div>
                {% if user_passes_test %}
                <a href="{% url 'update_comment' comment.pk %}" class="btn btn-primary btn-sm"> Edit </a>
                <a href="{% url 'delete_comment' comment.pk %}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this comment?')">Delete</a>
                {% endif %}
              </div>
            </li>
          {% endfor %}
        </ul>
      </div>

      <a href="{% url 'add_comment' article.pk %}" class="btn btn-success"> Add a comment </a>
    </div>
  </div>
      {% endblock %}

templates/articles/list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    {% include 'partial/search_form.html' %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Created at</th>
            </tr>
        </thead>

        <tbody>
            {% for article in articles %}
            {% if article.is_deleted == False %} 
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'article_detail' article.pk %}">{{ article.title }}</a></td>
                <td>{{ article.author }}</td>
                <td>{{ article.created_at|date:"d M Y" }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        {% include 'partial/pagination.html' %} 
    {% endif %}

<div class="mt-3">
    <a href="{% url 'article_create' %}" class="btn btn-success">Create new</a>
</div>

<p>{{ article.author.username}}  {{ article.author.get_full_name }} </p>

{% endblock %}

templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit article</h1>

<form action="{% url 'article_update' article.pk %}" method="POST" class="{% if dark_mode %}dark-mode{% endif %}">
    {% csrf_token %}

    {{ form.errors }}

    <div class="mb-3"> 
        <label for="title" class="form-label">Article</label>
        <input type="text" class="form-control" name="title" id="title" placeholder="Input your name" value="{{ article.title }}">
    </div>

        <div class="mb-3"> 
            <label for="author" class="form-label">Author</label>
            <select class="form-select" id="author" name="author">
                <option selected>Choose Author</option>
                {% for author in authors %} 
                    <option value="{{ author.pk }} {% if author.pk == article.author.pk %}selected{% endif %}">
                        {{ author }}
                    </option>
                {% endfor %} 
            </select>
        </div>

        <div class="mb-3">
            <label for="body" class="form-label">Type here</label>
            <textarea class="form-control" name="body" id="body" rows="3">{{ article.body }}</textarea>
    </div>

    <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock%}